### ISSUE TITLE
Partial Update to N64 list.

### ISSUE THREAD

**Issue by 2Bane** [Handheld-Database/handheld-database#10]
https://docs.google.com/spreadsheets/d/19Q8hlohoAv1tmU7egPgluUMTvC9Bn1ypywFfA8kh9n4/edit?usp=sharing

Current progress on a second pass of the N64 compatibility list.

Good news is I've found a couple new configurations that work better. 

Bad news is its incompatible with the previous script use to parse it. Also still needs another day before its complete but I've formatted it a way that it should be easier to parse and expand on should it be necessary.

Changes 

Column A is now a letter Rank. P, G, S, B, F (Plat/Gold/Silver/Bronze/Faulty)
Column B is now Name
Column C is Recommended Core/Config name.
Column D-G is Test notes, With Row 1 being configuration major settings.
Column H is Special settings or compatibility notes for games with unique issues.

I have a question about the rankings. Theres Quite a few games that run completely fine but natively they don't render at a standard resolution (Resulting in letter and/or pillar boxing). Do you think these games should be ranked Platinum or Gold if that is the sole issue.

**Comment by ogregorio** [comment]
Wow!

Thank you very much for your cooperation. My initial question is whether I should merge your updates with existing games, or replace the current information with yours.

As for the rank, it is still not entirely clear how to resolve these issues, but I believe that gold is a good grade. Let's leave the platinum grade for those games where the emulation is flawless.

**Comment by 2Bane** [comment]
It's probably easier to replace just due to the changes compared to the first list.

Might as well wait until I finish the current round of testing so it can be done all at once. Should be done tomorrow, will have to see how much time I have.

**Comment by ogregorio** [comment]
I will then proceed with importing and adjusting the script!

Thank you for the contribution!

**Comment by 2Bane** [comment]
List is all done should be good to go. Hope it works out all right.

I'll be busy for the next few days, GL.

**Comment by ogregorio** [comment]
Imported successfully, could you check and give me a feedback?

**Comment by 2Bane** [comment]
Everything's looking great.
