### ISSUE TITLE
Improvement to new_fily.py.

### ISSUE THREAD

**Issue by meeeaCH** [Handheld-Database/handheld-database#8]
Please add a new imput to "new game" process. It would be good, if it asked for the game's name too, so I don't have to modify the .json files.

**Comment by ogregorio** [comment]
I will work on improving this script. I believe it can be much better!

**Comment by ogregorio** [comment]
Your issue have been fix, try again 👍

**Comment by meeeaCH** [comment]
I'll try it later. I just finnished adding 7 games to PORTS.

**Comment by meeeaCH** [comment]
I tested it, it works.
I forgot to mention, but it would be great if the script would make the .overview files too. Using the "key" as the name from the .json file and with a check to see if it already exist.

I'll try to make this change, but I didn't really use python to much. Last time touched it was 2 years ago.

**Comment by ogregorio** [comment]
I made some improvements to the script, adding support for scraping descriptions, cover images, and icons. I also implemented your idea of creating templates for scenarios like ports and emulators. Thanks for the suggestion!

**Comment by meeeaCH** [comment]
I made some more changes to the script, they are mainly prints, so its more user friendly. I'll add my changes to the new script than and you can decide if they are needed or not.

Oh, you made more changes than I thought. I'll add things to where I can. For example, templates.
